# Generated by Django 3.2.4 on 2022-02-04 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeunit',
            name='education_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(to='students.Course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='time_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.timeunit'),
        ),
        migrations.AddField(
            model_name='student',
            name='only_contacted',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.onlycontacted'),
        ),
        migrations.AddField(
            model_name='student',
            name='selected_course',
            field=models.ManyToManyField(to='students.Course'),
        ),
        migrations.AddField(
            model_name='onlycontacted',
            name='advertisement',
            field=models.ManyToManyField(to='students.Advertisement'),
        ),
        migrations.AddField(
            model_name='onlycontacted',
            name='course_interested',
            field=models.ManyToManyField(to='students.Course'),
        ),
        migrations.AddField(
            model_name='onlycontacted',
            name='education_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='education_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='time_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.timeunit'),
        ),
        migrations.AddField(
            model_name='attendedmocklesson',
            name='lesson_attended',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.course'),
        ),
        migrations.AddField(
            model_name='attendedmocklesson',
            name='onlyContacted',
            field=models.ManyToManyField(to='students.OnlyContacted'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='education_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
