# Generated by Django 3.2.4 on 2022-02-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='speciality',
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(to='students.Course'),
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
