# Generated by Django 3.2.4 on 2022-02-04 20:00

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=students.models.generate_random_id, max_length=10, unique=True),
        ),
    ]
