# Generated by Django 3.2.4 on 2022-02-05 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost_for_month',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.TextField(choices=[("So'm", "So'm"), ('$', '$')], default="So'm"),
        ),
        migrations.AddField(
            model_name='student',
            name='total_payment_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('penalty_in_percent', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('education_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
