# Generated by Django 3.2.4 on 2022-02-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20220205_0549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendedMockLesson',
        ),
    ]
