# Generated by Django 3.2.4 on 2022-02-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_delete_attendedmocklesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cost_for_month',
            new_name='cost_per_month',
        ),
        migrations.AddField(
            model_name='student',
            name='penalty',
            field=models.ManyToManyField(to='students.Penalty'),
        ),
    ]
