# Generated by Django 3.2.4 on 2022-02-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20220205_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlycontacted',
            name='has_been_student',
            field=models.BooleanField(default=False),
        ),
    ]
