version: "3"

services:
  app:
    build: .

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db

    ports:
      - 8000:8000


  db:
    image: postgres:9.6
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
